### ISSUE TITLE
code is not complete?

### ISSUE THREAD

**Issue by ruanjiyang** [MB-29/optimal-textures#1]
Dear MB-29

I'm very interesting with this "optimal-textures", but it looks the code is not complete?

there is no "utils" module.

could you please complete the code? thanks!

**Comment by ruanjiyang** [comment]
could you please provide the following weights files? thanks.

Relu1_1_decoder_state.pth
Relu2_1_decoder_state.pth
Relu3_1_decoder_state.pth
Relu4_1_decoder_state.pth
Relu5_1_decoder_state.pth

**Comment by tobyj2** [comment]
Dear MB,

I would also like the pre-trained decoder weights. Please get back to me ASAP.

**Comment by sngdng** [comment]
Hi @MB-29,
I'm also interested in the pre-trained weights. The code looks complete to me, thank you.
