### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by moonmoonCL** [MB-29/optimal-textures#2]
I used the WCT decoder,  but the results were bad , like this 
![generated_texture](https://user-images.githubusercontent.com/55181046/111464957-72575880-875c-11eb-999e-1acbe68658bf.png)

Why?

**Comment by MB-29** [comment]
Hello, we did face this issue as well for images of some kind. The solution we've come up with is training a new decoder on the texture of your choice.

**Comment by moonmoonCL** [comment]
Oh, thanks!
